services:
  - type: web
    name: your-app-name
    env: php
    buildCommand: composer install && npm ci && npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: app-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: app-database
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: app-database
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: app-database
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: app-database
          property: password

databases:
  - name: app-database
    databaseName: your_database_name
    user: your_database_user
